### ISSUE TITLE
Fix deploy so my previous PR goes through

### ISSUE THREAD

**Issue by MarkKremer** [gorgonia/gorgonia.github.io#111]
The deployment github action doesn't work right now because Github deprecated `set-path` used by the Hugo deploy action. You can see the error here: https://github.com/gorgonia/gorgonia.github.io/runs/2294144853

This should be fixed by bumping [this version number](https://github.com/gorgonia/gorgonia.github.io/blob/e34b723ba2733529111871b3694d324d15ec4008/.github/workflows/gh-pages.yml#L18) to a newer version according to the reply to [this issue](https://github.com/peaceiris/actions-hugo/issues/470). If that has any side-effects, I don't know.

**Comment by owulveryck** [comment]
Let’s give it a try.
Thank you
