### ISSUE TITLE
translate "hello world" in French

### ISSUE THREAD

**Issue by owulveryck** [gorgonia/gorgonia.github.io#96]

**Comment by sundar-10** [comment]
Meaning? You can just use just use google translate?

**Comment by hikky08** [comment]
I would  love to work on this, where should hello world be translated, I need more info

**Comment by owulveryck** [comment]
Hi @hikky08, thanks for your interest.
You need to create a PR containing a file `content/tutorials/hello-world.fr.md` containing a translation of  `https://github.com/gorgonia/gorgonia.github.io/blob/develop/content/tutorials/hello-world.fr.md`

Hope it helps

**Comment by hikky08** [comment]
There is nothing like that there

**Comment by chewxy** [comment]
@hikky08  What @owulveryck  means is to translate this : https://github.com/gorgonia/gorgonia.github.io/blob/develop/content/tutorials/hello-world.md and save the file as `hello-world.fr.md` in the same directory

**Comment by hikky08** [comment]
oh, thanks
